// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.22.2";

// src/lib/mcp/tools/list-rooms.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.2";

// src/data/rooms-info.ts
var commonAmenities = [
  "Wi-Fi de alta velocidade",
  "Ar condicionado",
  "Pavimento radiante na casa de banho",
  "Amenities de banho",
  "Roup\xE3o de banho turco",
  "Cofre",
  "Mini-bar",
  "Chaleira"
];
var roomsInfo = [
  {
    slug: "standard",
    name: "Standard",
    count: "Ponto de partida",
    short: "Um ref\xFAgio simples e acolhedor, ideal para estadias curtas.",
    guests: "2 h\xF3spedes",
    bed: "Cama king-size",
    description: [
      "O quarto Standard \xE9 o ponto de partida da casa: espa\xE7o acolhedor, luz natural e um enquadramento sereno sobre o p\xE1tio interior.",
      "Um ref\xFAgio simples e acolhedor, ideal para estadias curtas em Sintra."
    ],
    amenities: commonAmenities
  },
  {
    slug: "deluxe",
    name: "Deluxe",
    count: "Um passo a cima",
    short: "Um espa\xE7o tranquilo e confort\xE1vel, pensado para proporcionar uma estadia agrad\xE1vel e especial.",
    guests: "2 h\xF3spedes",
    bed: "Cama king-size",
    description: [
      "Um espa\xE7o tranquilo e confort\xE1vel, pensado para proporcionar uma estadia agrad\xE1vel e especial.",
      "Restauradas a partir das alas originais do palacete setecentista, as su\xEDtes Deluxe conservam tectos altos, soalhos largos em pinho e detalhes em azulejo do s\xE9culo XVIII."
    ],
    amenities: commonAmenities
  },
  {
    slug: "superior",
    name: "Superior",
    count: "Uma experi\xEAncia Superior",
    short: "Mais espa\xE7o, mais conforto, uma experi\xEAncia Superior.",
    guests: "2 h\xF3spedes",
    bed: "Cama king-size",
    description: [
      "Um passo acima do Standard, o quarto Superior oferece mais \xE1rea, uma zona de estar e vista sobre o jardim.",
      "Mais espa\xE7o, mais conforto \u2014 uma experi\xEAncia Superior, sem renunciar \xE0 discri\xE7\xE3o da casa."
    ],
    amenities: commonAmenities
  },
  {
    slug: "penthouse",
    name: "Penthouse",
    count: "O ponto mais alto da casa",
    short: "Suite familiar equipada com kitchenette, sala de estar e banheira de hidromassagem.",
    guests: "2\u20134 h\xF3spedes",
    bed: "Cama king + sof\xE1-cama",
    description: [
      "A penthouse ocupa todo o \xFAltimo piso da torre original. Suite familiar equipada com kitchenette, sala de estar e banheira de hidromassagem.",
      "Pensada para ocasi\xF5es raras \u2014 um anivers\xE1rio, uma lua-de-mel, uma escapadinha em fam\xEDlia com a paisagem como \xFAnica companhia."
    ],
    amenities: commonAmenities
  },
  {
    slug: "loft",
    name: "Loft",
    count: "Est\xFAdio acolhedor",
    short: "Um ambiente amplo e descontra\xEDdo, que combina conforto e personalidade para uma estadia diferente.",
    guests: "2 h\xF3spedes",
    bed: "Cama queen-size",
    description: [
      "Um ambiente amplo e descontra\xEDdo, que combina conforto e personalidade para uma estadia diferente.",
      "O Loft \xE9 o espa\xE7o mais informal da casa \u2014 perfeito para quem procura liberdade e car\xE1cter em Sintra."
    ],
    amenities: commonAmenities
  }
];
var getRoomInfo = (slug) => roomsInfo.find((r) => r.slug === slug);

// src/lib/mcp/tools/list-rooms.ts
var list_rooms_default = defineTool({
  name: "list_rooms",
  title: "List rooms",
  description: "List all rooms at Pa\xE7o do Bispo boutique house with slug, name, short description, guest capacity and bed type.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const summary = roomsInfo.map((r) => ({
      slug: r.slug,
      name: r.name,
      count: r.count,
      short: r.short,
      guests: r.guests,
      bed: r.bed
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(summary, null, 2) }],
      structuredContent: { rooms: summary }
    };
  }
});

// src/lib/mcp/tools/get-room.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z } from "npm:zod@^4.4.3";
var get_room_default = defineTool2({
  name: "get_room",
  title: "Get room details",
  description: "Return full details for a single room by slug: description, amenities, capacity and bed type. Use list_rooms to discover valid slugs.",
  inputSchema: {
    slug: z.string().min(1).describe(`Room slug. One of: ${roomsInfo.map((r) => r.slug).join(", ")}`)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ slug }) => {
    const room = getRoomInfo(slug);
    if (!room) {
      return {
        content: [
          {
            type: "text",
            text: `No room found with slug "${slug}". Available: ${roomsInfo.map((r) => r.slug).join(", ")}.`
          }
        ],
        isError: true
      };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(room, null, 2) }],
      structuredContent: { room }
    };
  }
});

// src/lib/mcp/tools/contact-info.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.2";
var contact_info_default = defineTool3({
  name: "get_contact_info",
  title: "Get contact info",
  description: "Return contact details for Pa\xE7o do Bispo boutique house: reservations email and location.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const info = {
      name: "Pa\xE7o do Bispo Boutique House",
      reservationsEmail: "geral@pacodobispoboutiquehouse.com",
      location: "Sintra, Portugal",
      website: "https://pacodobispo.com"
    };
    return {
      content: [{ type: "text", text: JSON.stringify(info, null, 2) }],
      structuredContent: info
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "paco-do-bispo-mcp",
  title: "Pa\xE7o do Bispo",
  version: "0.1.0",
  instructions: "Public tools for Pa\xE7o do Bispo boutique house in Sintra. Use `list_rooms` to browse available rooms, `get_room` for full details of a room by slug, and `get_contact_info` for reservations and location.",
  tools: [list_rooms_default, get_room_default, contact_info_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
