// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.22.2";

// src/lib/mcp/tools/list-rooms.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.2";
import { rooms } from "npm:@/data/rooms";
var list_rooms_default = defineTool({
  name: "list_rooms",
  title: "List rooms",
  description: "List all rooms at Pa\xE7o do Bispo boutique house with slug, name, short description, size, guest capacity, bed type and view.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const summary = rooms.map((r) => ({
      slug: r.slug,
      name: r.name,
      count: r.count,
      short: r.short,
      size: r.size,
      guests: r.guests,
      bed: r.bed,
      view: r.view
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(summary, null, 2) }],
      structuredContent: { rooms: summary }
    };
  }
});

// src/lib/mcp/tools/get-room.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z } from "npm:zod@^4.4.3";
import { getRoom, rooms as rooms2 } from "npm:@/data/rooms";
var get_room_default = defineTool2({
  name: "get_room",
  title: "Get room details",
  description: "Return full details for a single room by slug: description, amenities, size, capacity and view. Use list_rooms to discover valid slugs.",
  inputSchema: {
    slug: z.string().min(1).describe(`Room slug. One of: ${rooms2.map((r) => r.slug).join(", ")}`)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ slug }) => {
    const room = getRoom(slug);
    if (!room) {
      return {
        content: [
          {
            type: "text",
            text: `No room found with slug "${slug}". Available: ${rooms2.map((r) => r.slug).join(", ")}.`
          }
        ],
        isError: true
      };
    }
    const { hero: _h, gallery: _g, ...data } = room;
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { room: data }
    };
  }
});

// src/lib/mcp/tools/contact-info.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.2";
var contact_info_default = defineTool3({
  name: "get_contact_info",
  title: "Get contact info",
  description: "Return contact details for Pa\xE7o do Bispo boutique house: reservations email and location.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const info = {
      name: "Pa\xE7o do Bispo Boutique House",
      reservationsEmail: "reservas@pacodobispo.com",
      location: "Sintra, Portugal",
      website: "https://pacodobispo.com"
    };
    return {
      content: [{ type: "text", text: JSON.stringify(info, null, 2) }],
      structuredContent: info
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "paco-do-bispo-mcp",
  title: "Pa\xE7o do Bispo",
  version: "0.1.0",
  instructions: "Public tools for Pa\xE7o do Bispo boutique house in Sintra. Use `list_rooms` to browse available rooms, `get_room` for full details of a room by slug, and `get_contact_info` for reservations and location.",
  tools: [list_rooms_default, get_room_default, contact_info_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
